### ISSUE TITLE
Tooling API version older than 3.0 in sts 3.9.1.201710100515-RELEASE

### ISSUE THREAD

**Issue by yin-bp** [spring-projects/eclipse-integration-gradle#110]
Support for clients using a tooling API version older than 3.0 was deprecated and will be removed in Gradle 5.0. You are currently using tooling API version 2.2.1. You should upgrade your tooling API client to version 3.0 or later.

**Comment by paulvi** [comment]
Unfortunately, that may be the end of this solution, as Pivotal stated long before, that this project is now under minimal maintenance.

Actually because Gradle Inc is developing Buildship Gradle integration under Eclipse foundation,
they may decide, when to bump version to 5.0, depending on when Buildship Gradle is good enough.

Of course Pull Request should be welcomed here (or do your own fork), but that will be huge piece of work. And why to compete with Gradle Inc for gradle tools?.. There is however solution, that does not use tooling API at all, and should  https://github.com/de-jcup/egradle  
But majority of users wants to know just one.

**Comment by kdvolder** [comment]
@paulvi Is correct, we will not be doing major work to update to a newer version of the tooling API. We beleave the time is finally come and today, BuildShip really is the better choice. I'm sure there are still some folks who haven't moved on, but it is probably time that they do. And, while there may be some pains adjusting to a new tool, in the end, I think they will probably be happy with the move. 

For the time being we will continue to offer the old gradle tooling 'as is' for little while longer. It may continue to work for people who are using old versions of Gradle. 

But in the not so distant future, probably a few months from now, we will probably stop building the tooling entirely.

I'm closing this ticket as we have no intention of updating to a newer version of the tooling api.
