### ISSUE TITLE
Mark Gradle's build directories as derived resources

### ISSUE THREAD

**Issue by tbrannt** [spring-projects/eclipse-integration-gradle#111]
Reopening https://jira.spring.io/browse/STS-2832

> By default the command-line gradle outputs to the project's build directory. The default Eclipse output is the bin directory. These should remain separate.
> 
> The Eclipse resource view includes the compiled files in the build directory. It would improve the usability if these directories were marked as "derived" when importing a project.
> 
> The workaround [1] of rewriting the project file to add resource filters is error prone and resulted in STS-2822. It would be nice if this was part of the plugin instead.
> 
> [1] http://forums.gradle.org/gradle/topics/eclipse_generated_files_should_be_put_in_the_same_place_as_the_gradle_generated_files

I came across the exact problem described in STS-2832 while using buildship. However this issue was closed with a hint to reopen it here.

**Comment by martinlippert** [comment]
We do only minimal maintenance work on this project at the moment and users should migrate over to use Buildship instead.

Therefore I am not exactly sure what you mean with your comment above about already using Buildship and coming across this problem, too. Is this a problem when using Buildship? Can you post a link to the discussion that you mentioned above (about the hint to post here), so that I can follow up there, too?

**Comment by paulvi** [comment]
@tbrannt Buildship issues are at https://github.com/eclipse/buildship

**Comment by tbrannt** [comment]
Sorry, intended to open this in the buildship repo
