### ISSUE TITLE
Refresh hooks?

### ISSUE THREAD

**Issue by TrentBartlem** [spring-projects/eclipse-integration-gradle#76]
Other Eclipse plugins (maven etc) allow users to specify, on a per-project basis, which tasks to run as part of refreshing the project, which also covers the initial refresh after checking it out of source control.

This allows a project to automatically trigger gradle tasks on checkout, which is a significant QOL improvement.

**Comment by BoykoAlex** [comment]
The Gradle project import wizard page has “Run before” and “Run after” check boxes at the top of the “Import options” group of controls. See the screenshot below.



Tasks to run are in the text boxes. Tasks in the text boxes separated by spaces are the tasks that would be run before and after the project is imported into Eclipse. Same tasks are run when the project is refreshed. Refreshing the project really removes the project and then imports it back in. Therefore, those are probably the tasks you’re looking for. The limitation is that these tasks can only be specified once during the import and will be executed for each refresh. Also these tasks come from the root project rather than from a specific subproject that you’d like to refresh…

Feel free to suggest the functionality that you’d like to have for such a hook. Please document it in a JIRA issue against GRADLE component here: https://issuetracker.springsource.com

**Comment by TrentBartlem** [comment]
Thanks.
