### ISSUE TITLE
What is the roadmap for this plugin with the presence of the BuildShip plugin?

### ISSUE THREAD

**Issue by davidmichaelkarr** [spring-projects/eclipse-integration-gradle#93]
I've used this plugin since I started using Gradle.  Several months ago I had heard that this plugin would be deprecated and replaced with the BuildShip plugin from GradleWare, at least in terms of the primary Gradle plugin for Eclipse.

In that context, I was surprised to see a new release of this come out, and even a pending one in the near future (3.7.1?).

BuildShip is apparently still pretty rudimentary, but what is the plan for this Gradle Eclipse plugin now that BuildShip is on the horizon?

**Comment by kdvolder** [comment]
The plan is to eventually abandon the project in favor of buildship. There is no real time-line or plan for this. At the moment we can't simply abandon this project because we have some things that depend on it. Build-ship isn't yet at a point where we can just replace e-i-gradle with it.

So we are continuing to maintain e-i-gradle for now and plan to keep an eye out on how build-ship is shaping up.

**Comment by paulvi** [comment]
Should this be in README?
